### ISSUE TITLE
Got a error.

### ISSUE THREAD

**Issue by dragonfire1119** [palanik/lumen-cors#1]
```
Problem 1
    - Installation request for laravel/lumen dev-develop -> satisfiable by laravel/lumen[dev-develop].
    - palanik/lumen-cors dev-master requires laravel/lumen >=5.0.0 -> satisfiable by laravel/lumen[v5.0.0, v5.0.1].
    - Can only install one of: laravel/lumen[v5.0.0, dev-develop].
    - Can only install one of: laravel/lumen[v5.0.1, dev-develop].
    - Installation request for palanik/lumen-cors dev-master -> satisfiable by palanik/lumen-cors[dev-master].
```

Are you going to be supporting v5.0.1?

**Comment by palanik** [comment]
@dragonfire1119, I've updated the code base and new set of instructions. Could you try again and let me know.

Thanks.
- P

**Comment by dragonfire1119** [comment]
I'll try it again. I got it to work by manually moving the lumen_cors to the middleware. I'm hoping to get composer to work so if you have any update I can just update composer.

**Comment by palanik** [comment]
Yes. Pushed the updates to composer.

**Comment by dragonfire1119** [comment]
@palanik Thanks for the fix for composer looks like it worked. I was wondering when I call the api route with angularjs $http it calls options method before the get or post method so I have to right now use the ``

```
// I would like not to have to put options route in on every route I make.
$app->options('post', 'ExampleController@index');
$app->get('post', 'ExampleController@index');
```

Then when I don't put the options in the route it, comes back with the cors error. Do you have to put the options method in with every api route? I don't know if it's a problem with lumen cors or nikic/FastRoute.

It's called "CORS pre-flight OPTIONS requests".

Thanks for your time and for making lumen cors.

**Comment by palanik** [comment]
Yes. 

Looks like your api endpoint is a preflighted request (POST with json?) as against a simple request.

For preflighted requests, the browser first sends a OPTIONS request followed by the actual POST request.

More info. here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests

lumen-cors supports preflighted requests. But, you need to add the OPTIONS route. No need to return any content for the OPTIONS.

**Comment by dragonfire1119** [comment]
@palanik Ya it works fine when I add a options route above each new route. I was wondering if there is a way to allow options route globally instead of adding it to the routes.php.

**Comment by vluzrmos** [comment]
Hey,

I resolve the OPTIONS trouble making a route options to any request:

``` php
public function register()
    {
        /** @var \Illuminate\Http\Request $request */
        $request = $this->app->make('request');

        app()->options($request->path(), function(){
            return new Response('OK', 200);
        });
    }
```

on my AppServiceProvider.

See the complete solution here: https://gist.github.com/vluzrmos/1238a0c81bfd90853f58

**Comment by dragonfire1119** [comment]
@vluzrmos When I add it to the AppServiceProvider it doesn't work `405 Method Not Allowed` is now what I'm getting.

**Comment by vluzrmos** [comment]
@dragonfire1119 I'm using right now that solution [Vluzrmos Lumen CORS](https://gist.github.com/vluzrmos/1238a0c81bfd90853f58) with AngularJS. that works fine....
Sometimes, when occurs an 500 (internal server error) it says "Method not allowed", but ... you have to fix the 500 error.

**Comment by dragonfire1119** [comment]
@vluzrmos There's no 500 errors when I use the lumen cors & manually use the options routes.

```
$app->options('/api/post', 'PostController@index');
$app->get('/api/post', 'PostController@index');
```

So there's something wrong with the AppServiceProvider. Seems like when you get a longer url example `api/test` will work but when you do something like `api/test/{id}/example` that calls Method not allowed. The options route for the second one goes through with a 200 but not the real route. There's also nothing in the lumen.log.

UPDATE:

https://gist.github.com/dragonfire1119/6ac56afa6f77710f4f66

This works.
