### ISSUE TITLE
Wrong settings access for exposeHeaders

### ISSUE THREAD

**Issue by robycup** [palanik/lumen-cors#10]
In setExposeHeaders the associative array settings is accessed with arrow operator:
$this->settings->exposeHeaders (lines 26 - 27).
Should not be $this->settings['exposeHeaders']?

**Comment by palanik** [comment]
@robycup Thanks for the PR.
Published as [v0.0.3](https://packagist.org/packages/palanik/lumen-cors#v0.0.3).
