### ISSUE TITLE
Why I got not allowed access?

### ISSUE THREAD

**Issue by hopewise** [palanik/lumen-cors#5]
I have defined a route like this:

```
$app->group(['middleware' => 'cors', 'namespace' => 'App\Http\Controllers'], function($app)  {
    $app->get('/territory/check_in', 'Territories@check_in');
});
```

Currently the page that calls the api is at: `http://192.168.99.100:9900`
And the end point api is: `http://192.168.99.100:9907/territory/check_in`

However, when I call it from javascript on another host, I got this error:

`XMLHttpRequest cannot load http://192.168.99.100:9907/territory/check_in. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.99.100:9900' is therefore not allowed access. The response had HTTP status code 405.`

Although its currently wide open for any origin.

I call it like this:

```
$('#check_in').click(function(){
                $.ajax({
                    url: 'http://192.168.99.100:9907/territory/check_in',
                    type: "get",
                    data: {},
                    success: function(data){
                        alert(data);
                    }
                });
            });
```

Can you please advice?

**Comment by jazlopez** [comment]
Did you figure out this issue? I was wondering if the Cors issue is resolved by this repo

**Comment by hopewise** [comment]
I switched to https://github.com/neomerx/cors-illuminate and it worked fine
