### ISSUE TITLE
Not working for return response()->download();

### ISSUE THREAD

**Issue by KevinBeckers** [palanik/lumen-cors#9]
Not working for return response()->download();
I have cors as global middleware.

Error:
Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::header()

**Comment by yingliangzhang** [comment]
Having the same issue here

**Comment by KevinBeckers** [comment]
I solved this by changing the handle method.
See comment in code:

```
/**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next) {

        if ($request->isMethod('OPTIONS')) {
            $response = new Response("", 200);
        }
        else {
            $response = $next($request);
        }

        // Added this to fix the image download problem
        // Only set Cors if its not een image
        if(strpos($response->headers->get('content-type'), 'image') === false) {
          $this->setCorsHeaders($request, $response);
        }

        return $response;
    }
```

**Comment by piavgh** [comment]
Thank Kevin.
But what if the file is pdf? I tried "application/octet-stream" but it's not working

**Comment by KevinBeckers** [comment]
Could you try "application/pdf" ?

**Comment by IAmMukeshKumar** [comment]
KevinBeckers, Can you show me the full demo of using this middleware. I am new in laravel.

**Comment by oknixus** [comment]
omg, this package is so old.
How about committing a pr for this issue?
